In [ ]:
# pandas handle large amount of data , and make conclusion based on statistical theory
# by using pandas you can filter data as you want with requirement 
# pandas work with diff diff file format 


## # pandas has 3 type of data structure 

### series 
### dataframe 
### panel : panel is 3d conatin data 

In [1]:
import pandas as pd 
import numpy as np 

In [3]:
# series is 1d data structure  

data= [1,2,3,4,5,6] 

a=pd.Series(data)

print(a)
print(type(a))

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
<class 'pandas.core.series.Series'>


In [5]:
print(a[1])
print(a[5])

2
6


In [7]:
# to change dtype and name of series 


data1= [1,2,3,4] 

data1=pd.Series(data1 , dtype=float , name= 'pandasSer') 
data1

0    1.0
1    2.0
2    3.0
3    4.0
Name: pandasSer, dtype: float64

In [10]:
# creating series     dtype :  object bcoz of mixed data 

dis = {'name' : ['py' , 'c' , 'java'] , "por" :[11,22,33] , "rank" :[1,2,3]}
var1 = pd.Series(dis)
var1

name    [py, c, java]
por      [11, 22, 33]
rank        [1, 2, 3]
dtype: object

In [11]:
t1 = pd.Series(12 , index=[1,2,3,4,5])
t2 = pd.Series(12 , index=[1,2,3]) 

print(t1+t2)  # it work with missing data also 

1    24.0
2    24.0
3    24.0
4     NaN
5     NaN
dtype: float64


In [ ]:
# dataframe is 2d dtype 

In [16]:
data= [1,2,3,4] 

data=pd.DataFrame(data)
print(data)
print(type(data))

   0
0  1
1  2
2  3
3  4
<class 'pandas.core.frame.DataFrame'>


In [18]:
dis = {'name' : ['py' , 'c' , 'java'] , "no" :[11,22,33] , "rank" :[1,2,3]} 

pd.DataFrame(dis)  # here data should same in all value

name  no  rank
0    py  11     1
1     c  22     2
2  java  33     3

In [19]:
dis = {'name' : ['py' , 'c' , 'java'] , "no" :[11,22,33] , "rank" :[1,2,3]} 

pd.DataFrame(dis , columns=['name'])

name
0    py
1     c
2  java

In [20]:
dis = {'name' : ['py' , 'c' , 'java'] , "no" :[11,22,33] , "rank" :[1,2,3]} 

pd.DataFrame(dis , columns=['name' , 'rank'])

name  rank
0    py     1
1     c     2
2  java     3

In [21]:
dis = {'name' : ['py' , 'c' , 'java'] , "no" :[11,22,33] , "rank" :[1,2,3]} 

pd.DataFrame(dis , columns=['name' , 'rank']  , index= ['one' , 'two' ,'three'])

name  rank
one      py     1
two       c     2
three  java     3

In [56]:
dis = {'name' : ['py' , 'c' , 'java'] , "no" :[11,22,33] , "rank" :[1,2,3]} 

dis=pd.DataFrame(dis)

In [57]:
dis

name  no  rank
0    py  11     1
1     c  22     2
2  java  33     3

In [58]:
dis['name'][0]

'py'

In [59]:
dis['name'][2]


'java'

In [62]:
# only for row 
dis.loc[0]

name    py
no      11
rank     1
Name: 0, dtype: object

In [64]:
dis.loc[[0,1]]

name  no  rank
0   py  11     1
1    c  22     2

In [65]:
# for row and index 
dis.iloc[0:2, 0:2]

name  no
0   py  11
1    c  22

In [48]:
dis['rank'][2]

3

In [50]:
dis[['name' ,'rank']]

name  rank
0    py     1
1     c     2
2  java     3

In [53]:
list1= [[1,2,3,4,5,6] ,[11,22,33,44,55,66]] 

list1=pd.DataFrame(list1) 
print(list1)

    0   1   2   3   4   5
0   1   2   3   4   5   6
1  11  22  33  44  55  66


In [ ]:
# create data frame 

In [2]:
np.arange(1,21,1).reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [4]:
pd.DataFrame(data=np.arange(1,21,1).reshape(5,4) , index=['r1','r2','r3','r4','r5'], columns=['col1','col2','col3','col4'])

col1  col2  col3  col4
r1     1     2     3     4
r2     5     6     7     8
r3     9    10    11    12
r4    13    14    15    16
r5    17    18    19    20

In [5]:
df=pd.DataFrame(data=np.arange(1,21,1).reshape(5,4) , index=['r1','r2','r3','r4','r5'], columns=['col1','col2','col3','col4'])

In [6]:
df

col1  col2  col3  col4
r1     1     2     3     4
r2     5     6     7     8
r3     9    10    11    12
r4    13    14    15    16
r5    17    18    19    20

In [7]:
df.head()

col1  col2  col3  col4
r1     1     2     3     4
r2     5     6     7     8
r3     9    10    11    12
r4    13    14    15    16
r5    17    18    19    20

In [8]:
df.tail()

col1  col2  col3  col4
r1     1     2     3     4
r2     5     6     7     8
r3     9    10    11    12
r4    13    14    15    16
r5    17    18    19    20

In [9]:
table=pd.DataFrame(np.arange(2,41,2).reshape(4,5) ,index=['R1','R2','R3',"R4"] ,columns=['C1','C2','C3','C4','C5'] ,dtype= float) 

In [10]:
table

C1    C2    C3    C4    C5
R1   2.0   4.0   6.0   8.0  10.0
R2  12.0  14.0  16.0  18.0  20.0
R3  22.0  24.0  26.0  28.0  30.0
R4  32.0  34.0  36.0  38.0  40.0

In [11]:
type(df)   # it is type of datastructure which we create by using pandas 

pandas.core.frame.DataFrame

In [12]:
df.info()   # it will give you information abt your dataframe 

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, r1 to r5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    5 non-null      int32
 1   col2    5 non-null      int32
 2   col3    5 non-null      int32
 3   col4    5 non-null      int32
dtypes: int32(4)
memory usage: 120.0+ bytes


In [13]:
type(table)

pandas.core.frame.DataFrame

In [14]:
table.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, R1 to R4
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   C1      4 non-null      float64
 1   C2      4 non-null      float64
 2   C3      4 non-null      float64
 3   C4      4 non-null      float64
 4   C5      4 non-null      float64
dtypes: float64(5)
memory usage: 192.0+ bytes


In [15]:
df

col1  col2  col3  col4
r1     1     2     3     4
r2     5     6     7     8
r3     9    10    11    12
r4    13    14    15    16
r5    17    18    19    20

In [16]:
df.describe()      # it will describe you your dataframe info which mean,count,std,max,min

col1       col2       col3       col4
count   5.000000   5.000000   5.000000   5.000000
mean    9.000000  10.000000  11.000000  12.000000
std     6.324555   6.324555   6.324555   6.324555
min     1.000000   2.000000   3.000000   4.000000
25%     5.000000   6.000000   7.000000   8.000000
50%     9.000000  10.000000  11.000000  12.000000
75%    13.000000  14.000000  15.000000  16.000000
max    17.000000  18.000000  19.000000  20.000000

# indexing  

1) by using col name 
2) row index(loc)
3) by using row_index_no , col_index_no (.iloc)

### 1) by using col name 

In [17]:
df

col1  col2  col3  col4
r1     1     2     3     4
r2     5     6     7     8
r3     9    10    11    12
r4    13    14    15    16
r5    17    18    19    20

In [18]:
# if we want only 1 col from res df then

df['col1']

r1     1
r2     5
r3     9
r4    13
r5    17
Name: col1, dtype: int32

In [19]:
# if we want only 2 col from res df then   

df[['col1' ,'col2']]    # more than 1 col use []

col1  col2
r1     1     2
r2     5     6
r3     9    10
r4    13    14
r5    17    18

In [20]:
type(df['col1'])  # look 

pandas.core.series.Series

In [21]:
type(df[['col1' ,'col2']] )   # look 

pandas.core.frame.DataFrame

In [22]:
# series = either 1 row or 1 col 
# datfrmae= more than 1 col , row

### 2) row index(loc)  = by using row index name 


In [23]:
df

col1  col2  col3  col4
r1     1     2     3     4
r2     5     6     7     8
r3     9    10    11    12
r4    13    14    15    16
r5    17    18    19    20

In [24]:
df.loc['r2']   # it will give you row info 

col1    5
col2    6
col3    7
col4    8
Name: r2, dtype: int32

In [26]:
df.loc['r3']

col1     9
col2    10
col3    11
col4    12
Name: r3, dtype: int32

In [27]:
type(df.loc['r2'])

pandas.core.series.Series

In [28]:
df.loc[['r2','r3']] 

col1  col2  col3  col4
r2     5     6     7     8
r3     9    10    11    12

In [29]:
type(df.loc[['r2','r3']] )

pandas.core.frame.DataFrame

### 3) by using row_index_no , col_index_no (.iloc)   = combing row/col index

In [41]:
df

col1  col2  col3  col4
r1     1     2     3     4
r2     5     6     7     8
r3     9    10    11    12
r4    13    14    15    16
r5    17    18    19    20

In [ ]:
# if requirwe 9 10
         #    13 14 

In [42]:
df.iloc[2:4, 0:2]

col1  col2
r3     9    10
r4    13    14

In [43]:
df.iloc[2:4 , 2:]

col3  col4
r3    11    12
r4    15    16

In [44]:
df

col1  col2  col3  col4
r1     1     2     3     4
r2     5     6     7     8
r3     9    10    11    12
r4    13    14    15    16
r5    17    18    19    20

In [50]:
df.iloc[:, [0, 3]]   # col1 and col4 

col1  col4
r1     1     4
r2     5     8
r3     9    12
r4    13    16
r5    17    20

In [52]:
df.iloc[[0,4] ,]   # row 1 and 4

col1  col2  col3  col4
r1     1     2     3     4
r5    17    18    19    20

In [ ]:
#  hoe to convert data frame into array ? 

In [53]:
df.values

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [56]:
df.iloc[1: , 1:].values

array([[ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16],
       [18, 19, 20]])

## basic operation 

In [59]:
df

col1  col2  col3  col4
r1     1     2     3     4
r2     5     6     7     8
r3     9    10    11    12
r4    13    14    15    16
r5    17    18    19    20

In [60]:
# to check null values in df 

df.isnull()   # no null value present 

col1   col2   col3   col4
r1  False  False  False  False
r2  False  False  False  False
r3  False  False  False  False
r4  False  False  False  False
r5  False  False  False  False

In [63]:
df.isnull().sum()    # count of null valuse 

col1    0
col2    0
col3    0
col4    0
dtype: int64

In [81]:
df['col3'].value_counts()  # it will tell number present in how much time 

col3
3     1
7     1
11    1
15    1
19    1
Name: count, dtype: int64

In [82]:
df[['col3' ,'col2']].value_counts()

col3  col2
3     2       1
7     6       1
11    10      1
15    14      1
19    18      1
Name: count, dtype: int64

In [83]:
# to find unique val present  

df['col3'].unique()

array([ 3,  7, 11, 15, 19])

In [86]:
df

col1  col2  col3  col4
r1     1     2     3     4
r2     5     6     7     8
r3     9    10    11    12
r4    13    14    15    16
r5    17    18    19    20

In [84]:
# grester than val 
df>10

col1   col2   col3   col4
r1  False  False  False  False
r2  False  False  False  False
r3  False  False   True   True
r4   True   True   True   True
r5   True   True   True   True

In [89]:
df[df>10]         # to get ans in df 

col1  col2  col3  col4
r1   NaN   NaN   NaN   NaN
r2   NaN   NaN   NaN   NaN
r3   NaN   NaN  11.0  12.0
r4  13.0  14.0  15.0  16.0
r5  17.0  18.0  19.0  20.0

In [90]:
df['col3']>11  

r1    False
r2    False
r3    False
r4     True
r5     True
Name: col3, dtype: bool

In [97]:
df[df['col3']>11]

col1  col2  col3  col4
r4    13    14    15    16
r5    17    18    19    20

In [72]:

# Create a new dataframe with zeros
new_df = pd.DataFrame(np.zeros((5, 5)), columns=['col1', 'col2', 'col3', 'col4', 'col5'] , dtype='int')

# Set specific values to non-zero integers
new_df.at[1, 'col2'] = 1
new_df.at[2, 'col3'] = 3
new_df.at[3, 'col4'] = 4
new_df.at[4, 'col5'] = 56

# Replace all zero values with NaN
new_df.replace(0, np.nan, inplace=True)

print(new_df)




   col1  col2  col3  col4  col5
0   NaN   NaN   NaN   NaN   NaN
1   NaN   1.0   NaN   NaN   NaN
2   NaN   NaN   3.0   NaN   NaN
3   NaN   NaN   NaN   4.0   NaN
4   NaN   NaN   NaN   NaN  56.0


In [77]:
new_df.isnull()

col1   col2   col3   col4   col5
0  True   True   True   True   True
1  True  False   True   True   True
2  True   True  False   True   True
3  True   True   True  False   True
4  True   True   True   True  False

In [76]:
new_df.isnull().sum()    # in each col we have that much null value 

col1    5
col2    4
col3    4
col4    4
col5    4
dtype: int64

## Arithmatic opreation 

In [66]:
var =pd.DataFrame({'A':[1,2,3,4] , 'B' :[5,6,7,8]}) 

var

A  B
0  1  5
1  2  6
2  3  7
3  4  8

In [69]:
var['C'] = var['A'] + var['B'] 
var

A  B   C
0  1  5   6
1  2  6   8
2  3  7  10
3  4  8  12

In [72]:
var['C'] = var['A'] * var['B'] 
var

A  B   C
0  1  5   5
1  2  6  12
2  3  7  21
3  4  8  32

In [84]:
var1 = pd.DataFrame({'A' :[10,20,30,40]  , 'B':[11,22,33,80]}) 

var

A  B   C
0  1  5   5
1  2  6  12
2  3  7  21
3  4  8  32

In [85]:
var1['Gt']= var['A'] >= 20 
var1['Lt'] =var['B'] <= 10  

var1

A   B     Gt    Lt
0  10  11  False  True
1  20  22  False  True
2  30  33  False  True
3  40  80  False  True

In [86]:
var1.isnull().sum()

A     0
B     0
Gt    0
Lt    0
dtype: int64

## delete insert modify

In [107]:
var =pd.DataFrame({'A':[1,2,3,4] , 'B' :[5,6,7,8]}) 

var

A  B
0  1  5
1  2  6
2  3  7
3  4  8

In [108]:
# inser the column 

var.insert(1 , "2nd"  , var['A'])             # para  --> (col_index , col_name , data) 

print(var)

   A  2nd  B
0  1    1  5
1  2    2  6
2  3    3  7
3  4    4  8


In [109]:
var.insert(3 , "4nd"  , [77,88,99,00])             # para  --> (col_index , col_name , data) 

print(var)   # but data shoild be quivalent 

   A  2nd  B  4nd
0  1    1  5   77
1  2    2  6   88
2  3    3  7   99
3  4    4  8    0


In [110]:
var['no5'] = var['B'][0:2]    # look   # no need to to be equivalent data 
var

A  2nd  B  4nd  no5
0  1    1  5   77  5.0
1  2    2  6   88  6.0
2  3    3  7   99  NaN
3  4    4  8    0  NaN

### delete

In [111]:
vardel= var.pop('2nd')
vardel

0    1
1    2
2    3
3    4
Name: 2nd, dtype: int64

In [112]:
var

A  B  4nd  no5
0  1  5   77  5.0
1  2  6   88  6.0
2  3  7   99  NaN
3  4  8    0  NaN

In [113]:
del var['B']

In [114]:
var

A  4nd  no5
0  1   77  5.0
1  2   88  6.0
2  3   99  NaN
3  4    0  NaN